"""update table message

Revision ID: 13be713c8d83
Revises: 599a67b9b342
Create Date: 2022-04-14 13:39:08.192725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13be713c8d83'
down_revision = '599a67b9b342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'folder', 'account', ['account_id'], ['id'])
    op.drop_constraint('message_old_folder_id_fkey', 'message', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('message_old_folder_id_fkey', 'message', 'folder', ['old_folder_id'], ['id'])
    op.drop_constraint(None, 'folder', type_='foreignkey')
    # ### end Alembic commands ###
