"""add table participent and remove thread

Revision ID: 22ae32024dbc
Revises: c1d758017637
Create Date: 2022-04-25 09:51:40.870873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22ae32024dbc'
down_revision = 'c1d758017637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_account_id'), 'participant', ['account_id'], unique=False)
    op.create_index(op.f('ix_participant_created_at'), 'participant', ['created_at'], unique=False)
    op.create_index(op.f('ix_participant_deleted'), 'participant', ['deleted'], unique=False)
    op.create_index(op.f('ix_participant_email'), 'participant', ['email'], unique=False)
    op.create_index(op.f('ix_participant_name'), 'participant', ['name'], unique=False)
    op.create_index(op.f('ix_participant_updated_at'), 'participant', ['updated_at'], unique=False)
    op.drop_table('thread_folder_association')
    op.drop_index('ix_message_thread_id', table_name='message')
    op.drop_constraint('message_thread_id_fkey', 'message', type_='foreignkey')
    op.drop_column('message', 'thread_id')
    op.add_column('tracker', sa.Column('md5_header_id', sa.String(length=36), nullable=True))
    op.drop_index('ix_tracker_thread_id', table_name='tracker')
    op.drop_constraint('tracker_thread_id_fkey', 'tracker', type_='foreignkey')
    op.drop_column('tracker', 'thread_id')
    op.drop_index('ix_thread_account_id', table_name='thread')
    op.drop_index('ix_thread_created_at', table_name='thread')
    op.drop_index('ix_thread_deleted', table_name='thread')
    op.drop_index('ix_thread_last_message_at', table_name='thread')
    op.drop_index('ix_thread_subject', table_name='thread')
    op.drop_index('ix_thread_updated_at', table_name='thread')
    op.drop_table('thread')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker', sa.Column('thread_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key('tracker_thread_id_fkey', 'tracker', 'thread', ['thread_id'], ['id'])
    op.create_index('ix_tracker_thread_id', 'tracker', ['thread_id'], unique=False)
    op.drop_column('tracker', 'md5_header_id')
    op.add_column('message', sa.Column('thread_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key('message_thread_id_fkey', 'message', 'thread', ['thread_id'], ['id'])
    op.create_index('ix_message_thread_id', 'message', ['thread_id'], unique=False)
    op.create_table('thread_folder_association',
    sa.Column('thread_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('folder_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], name='thread_folder_association_folder_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], name='thread_folder_association_thread_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id', 'folder_id', name='thread_folder_association_pkey')
    )
    op.create_table('thread',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('starred', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_attachments', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('snippet', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('snippets', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='thread_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='thread_pkey')
    )
    op.create_index('ix_thread_updated_at', 'thread', ['updated_at'], unique=False)
    op.create_index('ix_thread_subject', 'thread', ['subject'], unique=False)
    op.create_index('ix_thread_last_message_at', 'thread', ['last_message_at'], unique=False)
    op.create_index('ix_thread_deleted', 'thread', ['deleted'], unique=False)
    op.create_index('ix_thread_created_at', 'thread', ['created_at'], unique=False)
    op.create_index('ix_thread_account_id', 'thread', ['account_id'], unique=False)
    op.drop_index(op.f('ix_participant_updated_at'), table_name='participant')
    op.drop_index(op.f('ix_participant_name'), table_name='participant')
    op.drop_index(op.f('ix_participant_email'), table_name='participant')
    op.drop_index(op.f('ix_participant_deleted'), table_name='participant')
    op.drop_index(op.f('ix_participant_created_at'), table_name='participant')
    op.drop_index(op.f('ix_participant_account_id'), table_name='participant')
    op.drop_table('participant')
    # ### end Alembic commands ###
