"""add thread model

Revision ID: 78f01144378d
Revises: 7ca445411790
Create Date: 2022-04-27 14:48:15.441650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78f01144378d'
down_revision = '7ca445411790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_account_id'), 'thread', ['account_id'], unique=False)
    op.create_index(op.f('ix_thread_created_at'), 'thread', ['created_at'], unique=False)
    op.create_index(op.f('ix_thread_deleted'), 'thread', ['deleted'], unique=False)
    op.create_index(op.f('ix_thread_last_message_at'), 'thread', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_thread_subject'), 'thread', ['subject'], unique=False)
    op.create_index(op.f('ix_thread_updated_at'), 'thread', ['updated_at'], unique=False)
    op.create_table('thread_folder_association',
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id', 'folder_id')
    )
    op.add_column('message', sa.Column('snippet', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'snippet')
    op.drop_table('thread_folder_association')
    op.drop_index(op.f('ix_thread_updated_at'), table_name='thread')
    op.drop_index(op.f('ix_thread_subject'), table_name='thread')
    op.drop_index(op.f('ix_thread_last_message_at'), table_name='thread')
    op.drop_index(op.f('ix_thread_deleted'), table_name='thread')
    op.drop_index(op.f('ix_thread_created_at'), table_name='thread')
    op.drop_index(op.f('ix_thread_account_id'), table_name='thread')
    op.drop_table('thread')
    # ### end Alembic commands ###
