"""add md5 message id and in reply to

Revision ID: 7ca445411790
Revises: 22ae32024dbc
Create Date: 2022-04-27 08:21:06.873334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca445411790'
down_revision = '22ae32024dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('md5_message_id', sa.String(length=36), nullable=True))
    op.add_column('message', sa.Column('md5_in_reply_to', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_message_md5_in_reply_to'), 'message', ['md5_in_reply_to'], unique=False)
    op.create_index(op.f('ix_message_md5_message_id'), 'message', ['md5_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_md5_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_md5_in_reply_to'), table_name='message')
    op.drop_column('message', 'md5_in_reply_to')
    op.drop_column('message', 'md5_message_id')
    # ### end Alembic commands ###
