"""add models storage

Revision ID: c1d758017637
Revises: 13be713c8d83
Create Date: 2022-04-19 08:51:23.602679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1d758017637'
down_revision = '13be713c8d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('filename', sa.String(length=1000), nullable=False),
    sa.Column('filetype', sa.String(length=1000), nullable=True),
    sa.Column('content_type', sa.String(length=1000), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('object_type', sa.String(length=1000), nullable=True),
    sa.Column('object_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=10000), nullable=False),
    sa.Column('has_virus', sa.Boolean(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_account_id'), 'storage', ['account_id'], unique=False)
    op.create_index(op.f('ix_storage_content_type'), 'storage', ['content_type'], unique=False)
    op.create_index(op.f('ix_storage_created_at'), 'storage', ['created_at'], unique=False)
    op.create_index(op.f('ix_storage_deleted'), 'storage', ['deleted'], unique=False)
    op.create_index(op.f('ix_storage_filename'), 'storage', ['filename'], unique=False)
    op.create_index(op.f('ix_storage_filetype'), 'storage', ['filetype'], unique=False)
    op.create_index(op.f('ix_storage_has_virus'), 'storage', ['has_virus'], unique=False)
    op.create_index(op.f('ix_storage_object_id'), 'storage', ['object_id'], unique=False)
    op.create_index(op.f('ix_storage_object_type'), 'storage', ['object_type'], unique=False)
    op.create_index(op.f('ix_storage_updated_at'), 'storage', ['updated_at'], unique=False)
    op.create_index(op.f('ix_storage_url'), 'storage', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_url'), table_name='storage')
    op.drop_index(op.f('ix_storage_updated_at'), table_name='storage')
    op.drop_index(op.f('ix_storage_object_type'), table_name='storage')
    op.drop_index(op.f('ix_storage_object_id'), table_name='storage')
    op.drop_index(op.f('ix_storage_has_virus'), table_name='storage')
    op.drop_index(op.f('ix_storage_filetype'), table_name='storage')
    op.drop_index(op.f('ix_storage_filename'), table_name='storage')
    op.drop_index(op.f('ix_storage_deleted'), table_name='storage')
    op.drop_index(op.f('ix_storage_created_at'), table_name='storage')
    op.drop_index(op.f('ix_storage_content_type'), table_name='storage')
    op.drop_index(op.f('ix_storage_account_id'), table_name='storage')
    op.drop_table('storage')
    # ### end Alembic commands ###
